import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,BarChart3,BookOpen,ChevronRight,ClipboardList,FileText,Globe,LayoutDashboard,LogOut,Mail,Menu,RefreshCw,Settings,ShieldCheck,Users,X,Zap} from 'lucide-react';
import './admin.css';

const session=()=>{try{return JSON.parse(localStorage.getItem('scaleflow_session')||'null')}catch{return null}};
async function request(path,options={}){const s=session();const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(s?.access_token?{Authorization:`Bearer ${s.access_token}`}:{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}

function Admin(){const[s,setS]=useState(session());const[health,setHealth]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[section,setSection]=useState('Overview');const[mobile,setMobile]=useState(false);
 useEffect(()=>{if(!s?.access_token){location.href='/';return}load()},[s]);
 async function load(){setLoading(true);setError('');try{const h=await fetch('/api/health').then(r=>r.json());setHealth(h)}catch(e){setError(e.message)}finally{setLoading(false)}}
 function logout(){localStorage.removeItem('scaleflow_session');location.href='/'}
 const items=[['Overview',LayoutDashboard],['Leads',ClipboardList],['Clients',Users],['Content',FileText],['Insights',BookOpen],['Settings',Settings]];
 return <div className="adminApp"><aside className={mobile?'open':''}><div className="adminLogo"><span>⌘</span><div>ScaleFlow <b>AI</b><small>ADMIN CONSOLE</small></div></div><nav>{items.map(([x,I])=><button className={section===x?'active':''} key={x} onClick={()=>{setSection(x);setMobile(false)}}><I size={17}/>{x}</button>)}</nav><div className="adminSideBottom"><div className="secure"><ShieldCheck size={15}/><span>Protected workspace</span></div><button onClick={logout}><LogOut size={16}/>Sign out</button></div></aside><main><header className="adminTop"><button className="mobileMenu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div><span>ADMIN / {section.toUpperCase()}</span><h1>{section}</h1></div><div className="topActions"><span className="liveDot"><i/>Production</span><button onClick={load}><RefreshCw size={16}/></button></div></header>{error&&<div className="adminError">{error}</div>}{section==='Overview'&&<Overview health={health} loading={loading}/>} {section==='Leads'&&<Panel icon={ClipboardList} title="Lead management" text="New inquiries will appear here when the production data layer is connected. The contact API is already isolated behind the backend." action="Configure lead storage"/>}{section==='Clients'&&<Panel icon={Users} title="Client accounts" text="Manage authenticated client accounts, verification state and workspace access from this console after Supabase production credentials are connected." action="Open authentication settings"/>}{section==='Content'&&<Panel icon={FileText} title="Website content" text="Centralize services, case studies, testimonials, homepage sections and SEO metadata here. The schema is prepared for database-backed CMS content." action="Review CMS schema"/>}{section==='Insights'&&<Panel icon={BookOpen} title="Insights & publishing" text="Create, edit and publish articles with SEO metadata, categories, cover media and publication state." action="Create article"/>}{section==='Settings'&&<Panel icon={Settings} title="Platform settings" text="Production environment status, authentication, email delivery and admin access controls." action="Review configuration"/>}</main></div>}
function Overview({health,loading}){const cards=[['Qualified leads','—','Awaiting data layer',ClipboardList],['Client accounts','—','Supabase auth',Users],['Published content','—','CMS ready',FileText],['Email delivery',health?.emailConfigured?'Ready':'Needs setup',health?.emailConfigured?'Resend connected':'Resend API key required',Mail]];return <div className="content"><div className="welcome"><div><span className="eyebrow">BUSINESS COMMAND CENTER</span><h2>Run ScaleFlow from one place.</h2><p>Monitor leads, clients, content and production services without exposing operational controls to public visitors.</p></div><button className="primaryAdmin" onClick={()=>location.href='/'}><Globe size={16}/> View website</button></div><div className="statGrid">{cards.map(([a,b,c,I])=><div className="stat" key={a}><div className="statIcon"><I size={18}/></div><span>{a}</span><strong>{b}</strong><small>{c}</small></div>)}</div><div className="adminGrid"><section className="panel"><div className="panelHead"><div><span className="eyebrow">SYSTEM HEALTH</span><h3>Production services</h3></div><Activity size={18}/></div><div className="healthRow"><span><i className="ok"/>Backend API</span><b>{loading?'Checking…':'Operational'}</b></div><div className="healthRow"><span><i className={health?.authConfigured?'ok':'warn'}/>Authentication</span><b>{health?.authConfigured?'Connected':'Needs configuration'}</b></div><div className="healthRow"><span><i className={health?.emailConfigured?'ok':'warn'}/>Email delivery</span><b>{health?.emailConfigured?'Connected':'Needs configuration'}</b></div></section><section className="panel"><div className="panelHead"><div><span className="eyebrow">ADMIN ROADMAP</span><h3>Production-ready controls</h3></div><Zap size={18}/></div>{[['Authentication','Supabase + email verification'],['CRM','Lead capture + pipeline'],['CMS','Pages, services, cases + blog'],['Analytics','Conversion and inquiry metrics']].map(x=><div className="road" key={x[0]}><span>{x[0]}</span><small>{x[1]}</small><ChevronRight size={15}/></div>)}</section></div></div>}
function Panel({icon:Icon,title,text,action}){return <div className="content"><section className="emptyPanel"><div className="bigIcon"><Icon size={26}/></div><span className="eyebrow">ADMIN MODULE</span><h2>{title}</h2><p>{text}</p><button className="primaryAdmin">{action}<ChevronRight size={16}/></button></section></div>}

createRoot(document.getElementById('admin-root')).render(<Admin/>);