import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{ArrowRight,Check,ChevronRight,Command,Database,Globe,Menu,MessageSquare,Play,ShieldCheck,Sparkles,X,Zap}from'lucide-react';import'./styles.css';
const services=[['AI Business Automation','Automate repetitive work, connect your tools and keep teams moving.'],['Custom Website Development','High-performance websites and CMS platforms built around business goals.'],['Lead Generation Systems','Turn traffic into qualified conversations with smart funnels and CRM workflows.'],['Business Software Solutions','Custom dashboards, portals and internal tools that fit your operation.']];
const cases=[['PropertyFlow CRM','Real Estate Technology','Lead management platform with automated follow-ups.'],['MedConnect Portal','Healthcare Technology','Appointment and patient communication experience.'],['ShopBoost AI','E-commerce','Conversion-focused storefront and intelligent customer journeys.']];
function App(){const[menu,setMenu]=useState(false);const[active,setActive]=useState('Home');const[modal,setModal]=useState(false);const[submitted,setSubmitted]=useState(false);const go=(id)=>{setActive(id);setMenu(false);document.getElementById(id.toLowerCase())?.scrollIntoView({behavior:'smooth'})};return <div className="app">
<header><a className="logo" onClick={()=>go('Home')}><span className="logoMark"><Command size={19}/></span>ScaleFlow<span>AI</span></a><nav>{['Home','Services','Work','Insights','Contact'].map(x=><button key={x} className={active===x?'active':''} onClick={()=>go(x)}>{x}</button>)}</nav><button className="headerCta" onClick={()=>setModal(true)}>Book a strategy call <ArrowRight size={16}/></button><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
{menu&&<div className="mobileNav">{['Home','Services','Work','Insights','Contact'].map(x=><button key={x} onClick={()=>go(x)}>{x}</button>)}<button onClick={()=>setModal(true)}>Book a strategy call</button></div>}
<main>
<section id="home" className="hero"><div className="heroCopy"><div className="eyebrow"><span className="pulse"/> Business systems, built for scale</div><h1>Automate your business.<br/><em>Convert more customers.</em></h1><p>ScaleFlow AI designs intelligent automation systems, digital experiences and software that help ambitious companies operate better and grow faster.</p><div className="actions"><button className="primary" onClick={()=>setModal(true)}>Book a strategy call <ArrowRight size={18}/></button><button className="secondary" onClick={()=>go('Work')}><Play size={16}/> Explore our work</button></div><div className="trust"><div className="avatars"><i>JD</i><i>AM</i><i>SK</i><i>+</i></div><div><b>Built for modern teams</b><small>From first idea to scalable system.</small></div></div></div><div className="heroVisual"><div className="orb"></div><div className="dashboard"><div className="dashTop"><span>Growth overview</span><span className="live"><i/> Live</span></div><div className="metric"><small>Qualified leads</small><strong>2,847</strong><b>+28.4%</b></div><div className="bars"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="miniRow"><div><small>Automation</small><strong>94.8%</strong></div><div><small>Conversion</small><strong>12.6%</strong></div></div></div><div className="floatCard"><Zap size={17}/><div><b>Workflow optimized</b><small>37 tasks automated</small></div></div></div></section>
<section className="logos"><span>Trusted by teams building the future</span><b>Northstar</b><b>Vertex</b><b>MONO</b><b>orbit</b><b>FOUNDATION</b></section>
<section id="services" className="section"><div className="sectionHead"><div><span className="label">WHAT WE DO</span><h2>Digital infrastructure<br/>that moves business forward.</h2></div><p>We combine strategy, design and engineering to create systems that solve real operational problems.</p></div><div className="serviceGrid">{services.map(([title,text],i)=><article className="service" key={title}><span className="number">0{i+1}</span><div className="serviceIcon">{[<Zap/>,<Globe/>,<MessageSquare/>,<Database/>][i]}</div><h3>{title}</h3><p>{text}</p><button onClick={()=>setModal(true)}>Explore service <ChevronRight size={15}/></button></article>)}</div></section>
<section className="process"><div><span className="label">OUR PROCESS</span><h2>From problem to<br/><em>working system.</em></h2></div><div className="steps">{[['01','Discover','Understand the business, users and bottlenecks.'],['02','Design','Turn strategy into a clear, conversion-focused experience.'],['03','Build','Engineer a fast, reliable and scalable product.'],['04','Optimize','Measure, improve and automate continuously.']].map(s=><div className="step" key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></div>)}</div></section>
<section id="work" className="section work"><div className="sectionHead"><div><span className="label">SELECTED WORK</span><h2>Systems designed<br/>around outcomes.</h2></div><button className="textBtn">View all projects <ArrowRight size={16}/></button></div><div className="caseGrid">{cases.map((c,i)=><article className="case" key={c[0]}><div className={'caseVisual v'+i}><div className="caseUI"><span>{c[1]}</span><strong>{i===0?'PropertyFlow':i===1?'MedConnect':'ShopBoost'}</strong><div className="fakeLines"><i/><i/><i/><i/></div></div></div><div className="caseInfo"><div><span>{c[1]}</span><h3>{c[0]}</h3><p>{c[2]}</p></div><button><ArrowRight/></button></div></article>)}</div></section>
<section id="insights" className="insights"><div><span className="label">LATEST INSIGHTS</span><h2>Ideas for building<br/>a better business.</h2></div><div className="posts"><article><span>Automation · 6 min</span><h3>Why modern businesses are replacing repetitive work with intelligent systems.</h3><button>Read article <ArrowRight size={15}/></button></article><article><span>Growth · 4 min</span><h3>Your website should be part of your sales process — not just your online brochure.</h3><button>Read article <ArrowRight size={15}/></button></article></div></section>
<section id="contact" className="cta"><div><span className="label">LET'S BUILD</span><h2>Have a business problem<br/>worth solving?</h2><p>Tell us what you're trying to improve. We'll help map the next step.</p></div><button className="lightBtn" onClick={()=>setModal(true)}>Start a conversation <ArrowRight size={17}/></button></section>
</main><footer><div className="footerBrand"><a className="logo"><span className="logoMark"><Command size={18}/></span>ScaleFlow<span>AI</span></a><p>Intelligent systems for ambitious businesses.</p></div><div><b>Company</b><button onClick={()=>go('Work')}>Work</button><button onClick={()=>go('Insights')}>Insights</button></div><div><b>Services</b>{services.slice(0,3).map(s=><button key={s[0]} onClick={()=>go('Services')}>{s[0]}</button>)}</div><div><b>Connect</b><button onClick={()=>setModal(true)}>Contact</button><button>LinkedIn ↗</button><button>Twitter / X ↗</button></div><div className="copyright">© 2026 ScaleFlow AI. All rights reserved.</div></footer>
{modal&&<div className="modalBg" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}>{submitted?<><div className="success"><Check size={28}/></div><h2>Thanks — message received.</h2><p>We'll review your project details and get back to you shortly.</p><button className="primary" onClick={()=>{setModal(false);setSubmitted(false)}}>Close</button></>:<><button className="close" onClick={()=>setModal(false)}><X/></button><span className="label">START A PROJECT</span><h2>Let's talk about your next system.</h2><p>Tell us a little about what you're building.</p><form onSubmit={e=>{e.preventDefault();setSubmitted(true)}}><input required placeholder="Your name"/><input required type="email" placeholder="Work email"/><input placeholder="Company"/><select><option>What can we help with?</option>{services.map(s=><option key={s[0]}>{s[0]}</option>)}</select><textarea required placeholder="Tell us about your project..."/><button className="primary">Send inquiry <ArrowRight size={17}/></button></form></>}</div></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);