import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Check, ChevronRight, Command, Database, Globe, Lock, LogIn, LogOut, Mail, Menu, MessageSquare, Play, ShieldCheck, Sparkles, UserPlus, X, Zap } from 'lucide-react';
import './styles.css';

const services=[['AI Business Automation','Automate repetitive work, connect your tools and keep teams moving.','Zap'],['Custom Website Development','High-performance websites, CMS platforms and conversion systems built around business goals.','Globe'],['Lead Generation Systems','Turn traffic into qualified conversations with smart funnels, forms and CRM workflows.','MessageSquare'],['Business Software Solutions','Custom dashboards, portals and internal tools that fit your operation.','Database']];
const cases=[['PropertyFlow CRM','Real Estate Technology','Lead management, pipeline visibility and automated follow-up workflows.','https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=85'],['MedConnect Portal','Healthcare Technology','A patient-facing experience for appointments, communications and operations.','https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1400&q=85'],['ShopBoost AI','E-commerce','Conversion-focused storefront experiences and intelligent customer journeys.','https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=85']];
const posts=[['Automation','6 min','How intelligent workflows remove repetitive work without slowing your team down.'],['Growth','4 min','Why your website should be part of your sales process, not just your online brochure.'],['Systems','7 min','The practical architecture behind a scalable business website and client portal.']];
const iconFor=name=>({Zap,Globe,MessageSquare,Database}[name]||Sparkles);
const apiBase='/api';
function getSavedSession(){try{return JSON.parse(localStorage.getItem('scaleflow_session')||'null')}catch{return null}}
async function api(path,body={},token){const r=await fetch(`${apiBase}${path}`,{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed.');return d}

function App(){
 const[menu,setMenu]=useState(false),[active,setActive]=useState('Home'),[modal,setModal]=useState(null),[submitted,setSubmitted]=useState(false),[session,setSession]=useState(getSavedSession),[authMode,setAuthMode]=useState('login'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[profile,setProfile]=useState(null);
 const logged=Boolean(session?.access_token); const name=useMemo(()=>profile?.email?.split('@')[0]||session?.user?.email?.split('@')[0]||'Client',[profile,session]);
 useEffect(()=>{if(session?.access_token)fetch(`${apiBase}/me`,{headers:{Authorization:`Bearer ${session.access_token}`}}).then(async r=>{if(r.ok)setProfile((await r.json()).user)}).catch(()=>{})},[session]);
 const go=id=>{setActive(id);setMenu(false);document.getElementById(id.toLowerCase())?.scrollIntoView({behavior:'smooth'})};
 const openAuth=m=>{setAuthMode(m);setError('');setNotice('');setModal('auth')};
 async function authSubmit(e){e.preventDefault();setBusy(true);setError('');setNotice('');const f=new FormData(e.currentTarget);const email=String(f.get('email')||'').trim();const password=String(f.get('password')||'');try{if(authMode==='signup'){const d=await api('/auth/signup',{email,password,name:String(f.get('name')||'').trim()});if(d.session){localStorage.setItem('scaleflow_session',JSON.stringify(d.session));setSession(d.session);setModal('dashboard')}else{setNotice('Account created. Check your email and click the verification link before signing in.');setAuthMode('login')}}else{const d=await api('/auth/login',{email,password});localStorage.setItem('scaleflow_session',JSON.stringify(d.session));setSession(d.session);setModal('dashboard')}}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function resend(e){e.preventDefault();setBusy(true);setError('');setNotice('');const f=new FormData(e.currentTarget);try{await api('/auth/resend',{email:String(f.get('email')||'').trim()});setNotice('Verification email requested. Check your inbox and spam folder.')}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function logout(){try{if(session?.access_token)await api('/auth/logout',{},session.access_token)}catch{}localStorage.removeItem('scaleflow_session');setSession(null);setProfile(null);setModal(null);go('Home')}
 async function contact(e){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{await api('/contact',{name:f.get('name'),email:f.get('email'),company:f.get('company'),service:f.get('service'),message:f.get('message')});setSubmitted(true)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="app">
  <header><button className="logo" onClick={()=>go('Home')}><span className="logoMark"><Command size={19}/></span>ScaleFlow<span>AI</span></button><nav>{['Home','Services','Work','Insights','Contact'].map(x=><button key={x} className={active===x?'active':''} onClick={()=>go(x)}>{x}</button>)}</nav><div className="headerActions">{logged?<><button className="accountBtn" onClick={()=>setModal('dashboard')}><ShieldCheck size={16}/> Client portal</button><button className="headerCta" onClick={logout}><LogOut size={16}/> Log out</button></>:<><button className="loginBtn" onClick={()=>openAuth('login')}>Log in</button><button className="headerCta" onClick={()=>setModal('contact')}>Book a strategy call <ArrowRight size={16}/></button></>}</div><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
  {menu&&<div className="mobileNav">{['Home','Services','Work','Insights','Contact'].map(x=><button key={x} onClick={()=>go(x)}>{x}</button>)}<button onClick={()=>openAuth(logged?'login':'login')}>{logged?'Client portal':'Log in'}</button><button onClick={()=>setModal('contact')}>Book a strategy call</button></div>}
  <main>
   <section id="home" className="hero"><div className="heroCopy"><div className="eyebrow"><span className="pulse"/> Business systems, built for scale</div><h1>Build a business that<br/><em>runs smarter.</em></h1><p>ScaleFlow AI designs intelligent automation, digital experiences and software that help ambitious companies operate better, convert more customers and scale with confidence.</p><div className="actions"><button className="primary" onClick={()=>setModal('contact')}>Book a strategy call <ArrowRight size={18}/></button><button className="secondary" onClick={()=>go('Work')}><Play size={16}/> Explore our work</button></div><div className="trust"><div className="avatars"><i>JD</i><i>AM</i><i>SK</i><i>+</i></div><div><b>Built for modern teams</b><small>Strategy · Design · Engineering · Automation</small></div></div></div><div className="heroVisual"><div className="heroVideo"><div className="videoOverlay"><span><Play size={15}/> Workflow in motion</span><strong>Turn manual work into a system.</strong></div></div><div className="dashboard"><div className="dashTop"><span>Business command center</span><span className="live"><i/> Live</span></div><div className="metric"><small>Qualified opportunities</small><strong>2,847</strong><b>+28.4%</b></div><div className="bars"><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><div className="miniRow"><div><small>Automation</small><strong>94.8%</strong></div><div><small>Conversion</small><strong>12.6%</strong></div></div></div><div className="floatCard"><Zap size={17}/><div><b>Workflow optimized</b><small>37 tasks automated</small></div></div></div></section>
   <section className="logos"><span>Built around how modern B2B teams buy</span><b>Northstar</b><b>Vertex</b><b>MONO</b><b>orbit</b><b>FOUNDATION</b></section>
   <section id="services" className="section"><div className="sectionHead"><div><span className="label">WHAT WE DO</span><h2>Digital infrastructure<br/>that moves business forward.</h2></div><p>We combine strategy, design and engineering to create systems that solve real operational problems.</p></div><div className="serviceGrid">{services.map(([title,text,icon],i)=>{const Icon=iconFor(icon);return <article className="service" key={title}><span className="number">0{i+1}</span><div className="serviceIcon"><Icon/></div><h3>{title}</h3><p>{text}</p><button onClick={()=>setModal('contact')}>Explore service <ChevronRight size={15}/></button></article>})}</div></section>
   <section className="visualBreak"><div className="visualCopy"><span className="label">DESIGNED FOR REAL WORK</span><h2>Less busywork.<br/><em>More momentum.</em></h2><p>Clear information architecture, product-style interfaces, purposeful motion and business-focused visuals are common patterns across modern B2B SaaS and automation sites. citeturn0search0turn0search6</p><button className="secondary" onClick={()=>setModal('contact')}>Talk to an expert <ArrowRight size={16}/></button></div><div className="visualImage"><img src="https://images.unsplash.com/photo-1556761175-4b46a572b786?auto=format&fit=crop&w=1500&q=85" alt="Modern team collaborating around a business dashboard"/><div className="imageBadge"><Sparkles size={16}/><span>Strategy + systems</span></div></div></section>
   <section className="process"><div><span className="label">OUR PROCESS</span><h2>From problem to<br/><em>working system.</em></h2><p>Every engagement is structured around a measurable business outcome.</p></div><div className="steps">{[['01','Discover','Understand the business, users and bottlenecks.'],['02','Design','Turn strategy into a clear, conversion-focused experience.'],['03','Build','Engineer a fast, reliable and scalable product.'],['04','Optimize','Measure, improve and automate continuously.']].map(s=><div className="step" key={s[0]}><span>{s[0]}</span><div><h3>{s[1]}</h3><p>{s[2]}</p></div></div>)}</div></section>
   <section id="work" className="section work"><div className="sectionHead"><div><span className="label">SELECTED WORK</span><h2>Systems designed<br/>around outcomes.</h2></div><button className="textBtn" onClick={()=>setModal('contact')}>Start a project <ArrowRight size={16}/></button></div><div className="caseGrid">{cases.map(c=><article className="case" key={c[0]}><div className="caseVisual"><img src={c[3]} alt={c[0]}/><div className="caseUI"><span>{c[1]}</span><strong>{c[0]}</strong><div className="fakeLines"><i/><i/><i/><i/></div></div></div><div className="caseInfo"><div><span>{c[1]}</span><h3>{c[0]}</h3><p>{c[2]}</p></div><button onClick={()=>setModal('contact')}><ArrowRight/></button></div></article>)}</div></section>
   <section id="insights" className="insights"><div><span className="label">LATEST INSIGHTS</span><h2>Ideas for building<br/>a better business.</h2></div><div className="posts">{posts.map(p=><article key={p[2]}><span>{p[0]} · {p[1]}</span><h3>{p[2]}</h3><button onClick={()=>setModal('contact')}>Discuss this with us <ArrowRight size={15}/></button></article>)}</div></section>
   <section id="contact" className="cta"><div><span className="label">LET'S BUILD</span><h2>Have a business problem<br/>worth solving?</h2><p>Tell us what you're trying to improve. We'll help map the next step.</p></div><button className="lightBtn" onClick={()=>setModal('contact')}>Start a conversation <ArrowRight size={17}/></button></section>
  </main>
  <footer><div className="footerBrand"><button className="logo"><span className="logoMark"><Command size={18}/></span>ScaleFlow<span>AI</span></button><p>Intelligent systems for ambitious businesses.</p></div><div><b>Company</b><button onClick={()=>go('Work')}>Work</button><button onClick={()=>go('Insights')}>Insights</button></div><div><b>Services</b>{services.slice(0,3).map(s=><button key={s[0]} onClick={()=>go('Services')}>{s[0]}</button>)}</div><div><b>Connect</b><button onClick={()=>setModal('contact')}>Contact</button><button onClick={()=>openAuth('signup')}>Create client account</button><button>LinkedIn ↗</button><button>Twitter / X ↗</button></div><div className="copyright">© 2026 ScaleFlow AI. All rights reserved.</div></footer>
  {modal==='contact'&&<div className="modalBg" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}>{submitted?<><div className="success"><Check size={28}/></div><h2>Thanks — inquiry received.</h2><p>Your request has been sent to the ScaleFlow team.</p><button className="primary" onClick={()=>{setModal(null);setSubmitted(false)}}>Close</button></>:<><button className="close" onClick={()=>setModal(null)}><X/></button><span className="label">START A PROJECT</span><h2>Let's talk about your next system.</h2><p>Tell us a little about what you're building.</p>{error&&<div className="error">{error}</div>}<form onSubmit={contact}><input required name="name" placeholder="Your name"/><input required name="email" type="email" placeholder="Work email"/><input name="company" placeholder="Company"/><select name="service" defaultValue=""><option value="" disabled>What can we help with?</option>{services.map(s=><option key={s[0]}>{s[0]}</option>)}</select><textarea required name="message" placeholder="Tell us about your project..."/><button className="primary" disabled={busy}>{busy?'Sending…':'Send inquiry'} <ArrowRight size={17}/></button></form></>}</div></div>}
  {modal==='auth'&&<div className="modalBg" onClick={()=>setModal(null)}><div className="modal authModal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}><X/></button><div className="authIcon">{authMode==='login'?<LogIn/>:<UserPlus/>}</div><span className="label">CLIENT PORTAL</span><h2>{authMode==='login'?'Welcome back.':'Create your client account.'}</h2><p>{authMode==='login'?'Access project updates, requests and your ScaleFlow workspace.':'Create an account to securely access your client workspace.'}</p>{error&&<div className="error">{error}</div>}{notice&&<div className="notice">{notice}</div>}{authMode!=='resend'&&<form onSubmit={authSubmit}>{authMode==='signup'&&<input name="name" required placeholder="Full name"/>}<input name="email" required type="email" placeholder="Email address"/><input name="password" required minLength="8" type="password" placeholder="Password (8+ characters)"/><button className="primary" disabled={busy}>{busy?'Please wait…':authMode==='login'?'Log in securely':'Create account'} <ArrowRight size={17}/></button></form>}{authMode==='resend'&&<form onSubmit={resend}><input name="email" required type="email" placeholder="Your signup email"/><button className="primary" disabled={busy}><Mail size={16}/> Send verification email</button></form>}<div className="authLinks">{authMode==='login'?<><button onClick={()=>setAuthMode('signup')}>Create an account</button><button onClick={()=>setAuthMode('resend')}>Resend verification email</button></>:<button onClick={()=>setAuthMode('login')}>Back to login</button>}</div><small className="securityNote"><Lock size={13}/> Secure authentication and email verification are handled by the production auth backend.</small></div></div>}
  {modal==='dashboard'&&<div className="modalBg" onClick={()=>setModal(null)}><div className="portal" onClick={e=>e.stopPropagation()}><div className="portalTop"><div><span className="label">CLIENT PORTAL</span><h2>Welcome, {name}.</h2><p>Your private ScaleFlow workspace.</p></div><button className="close" onClick={()=>setModal(null)}><X/></button></div><div className="portalGrid"><div className="portalCard"><span>Account</span><strong>{profile?.email||session?.user?.email||'Authenticated client'}</strong><small><ShieldCheck size={14}/> Secure session active</small></div><div className="portalCard"><span>Projects</span><strong>Workspace ready</strong><small>Project requests and updates will appear here.</small></div><div className="portalCard wide"><span>Next step</span><strong>Start a project request</strong><p>Send requirements directly to the ScaleFlow team from your secure workspace.</p><button className="primary" onClick={()=>setModal('contact')}>New project request <ArrowRight size={16}/></button></div></div><button className="portalLogout" onClick={logout}><LogOut size={16}/> Sign out</button></div></div>}
 </div>
}
createRoot(document.getElementById('root')).render(<App/>);
