(function(){
const projects=[
{id:'propertyflow',name:'PropertyFlow CRM',type:'AI & Automation',industry:'Real Estate',year:'2026',image:'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=1800&q=88',summary:'A focused operating system for property teams to capture leads, manage pipelines and keep follow-up visible.',scope:['CRM','Lead automation','Dashboard'],accent:'01'},
{id:'medconnect',name:'MedConnect Portal',type:'Web & Product',industry:'Healthcare',year:'2026',image:'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1800&q=88',summary:'A calmer patient-facing digital experience for appointments, communication and day-to-day operations.',scope:['Portal','UX/UI','Workflow'],accent:'02'},
{id:'shopboost',name:'ShopBoost AI',type:'Commerce & Growth',industry:'E-commerce',year:'2026',image:'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1800&q=88',summary:'A conversion-focused storefront concept built around clearer product discovery and smarter customer journeys.',scope:['E-commerce','Conversion','Automation'],accent:'03'},
{id:'opsgrid',name:'OpsGrid',type:'AI & Automation',industry:'Operations',year:'2026',image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1800&q=88',summary:'A command-center concept that turns scattered operational activity into one readable workspace.',scope:['Internal tools','Analytics','Automation'],accent:'04'}
];
function mount(){
 if(document.body.dataset.page!=='Work')return;
 const root=document.getElementById('work');if(!root||root.dataset.customWork==='1')return;
 root.dataset.customWork='1';document.title='ScaleFlow AI — Selected Work';root.className='section work customWorkPage';
 root.innerHTML=`<div class="workIntro"><div><span class="label">SELECTED WORK / 2026</span><h2>We build the system<br><em>behind the experience.</em></h2></div><p>Explore concept builds across automation, product design, websites and business software. Each project is presented as a system story—not just a screenshot.</p></div><div class="workFilters" aria-label="Filter projects"><button class="workFilter isActive" data-filter="All">All work</button><button class="workFilter" data-filter="AI & Automation">AI & Automation</button><button class="workFilter" data-filter="Web & Product">Web & Product</button><button class="workFilter" data-filter="Commerce & Growth">Commerce & Growth</button></div><article class="workFeature"><div class="workFeatureImage"><img src="${projects[0].image}" alt="${projects[0].name}" loading="eager"><span class="workFeatureIndex">${projects[0].accent}</span></div><div class="workFeatureCopy"><div class="workMeta"><span>${projects[0].industry}</span><span>${projects[0].year}</span></div><h3>${projects[0].name}</h3><p>${projects[0].summary}</p><div class="workTags">${projects[0].scope.map(s=>`<span>${s}</span>`).join('')}</div><button class="workOpen" data-project="${projects[0].id}">View project <span>↗</span></button></div></article><div class="workGrid" id="workGrid"></div><div class="workBottom"><div><span class="label">THE APPROACH</span><h3>Strategy first.<br><em>Interfaces second.</em></h3></div><p>Good case studies explain the problem, the system and the decisions behind the interface. Visitors can now browse by capability and open a focused project view.</p></div><div class="workCaseModal" aria-hidden="true"><div class="workCaseBackdrop"></div><div class="workCaseDialog" role="dialog" aria-modal="true"><button class="workCaseClose" aria-label="Close">×</button><div class="workCaseMedia"><img alt=""></div><div class="workCaseBody"></div></div></div>`;
 const grid=root.querySelector('#workGrid'),modal=root.querySelector('.workCaseModal'),media=modal.querySelector('.workCaseMedia img'),body=modal.querySelector('.workCaseBody');
 function close(){modal.classList.remove('isOpen');modal.setAttribute('aria-hidden','true');document.body.classList.remove('workModalOpen')}
 function open(id){const p=projects.find(x=>x.id===id);if(!p)return;media.src=p.image;media.alt=p.name;body.innerHTML=`<span class="label">CASE STUDY / ${p.year}</span><h3>${p.name}</h3><p>${p.summary}</p><div class="workCaseStats"><div><span>Industry</span><strong>${p.industry}</strong></div><div><span>Focus</span><strong>${p.type}</strong></div><div><span>Scope</span><strong>${p.scope.join(' · ')}</strong></div></div><button class="workCaseCta" data-contact>Start a similar project <span>↗</span></button>`;modal.classList.add('isOpen');modal.setAttribute('aria-hidden','false');document.body.classList.add('workModalOpen');body.querySelector('[data-contact]').onclick=()=>{close();const c=document.querySelector('.headerCta');if(c)c.click()}}
 function cards(filter){const list=filter==='All'?projects.slice(1):projects.filter(p=>p.type===filter&&p.id!=='propertyflow');grid.innerHTML=list.length?list.map(p=>`<article class="workCard" data-project="${p.id}"><div class="workCardImage"><img src="${p.image}" alt="${p.name}" loading="lazy"><span>${p.accent}</span></div><div class="workCardInfo"><div class="workMeta"><span>${p.industry}</span><span>${p.year}</span></div><h3>${p.name}</h3><p>${p.summary}</p><div class="workCardFoot"><span>${p.type}</span><button class="workOpen" data-project="${p.id}">View case study ↗</button></div></div></article>`).join(''):`<div class="workEmpty">No projects in this category yet. Explore all work.</div>`;grid.querySelectorAll('[data-project]').forEach(el=>el.onclick=e=>{e.stopPropagation();open(el.dataset.project)});}
 root.querySelectorAll('.workFilter').forEach(b=>b.onclick=()=>{root.querySelectorAll('.workFilter').forEach(x=>x.classList.remove('isActive'));b.classList.add('isActive');cards(b.dataset.filter)});root.querySelector('.workOpen').onclick=()=>open(projects[0].id);modal.querySelector('.workCaseClose').onclick=close;modal.querySelector('.workCaseBackdrop').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});cards('All');
}
const boot=()=>{mount();if(!document.querySelector('[data-page="Work"]')&&document.body.dataset.page!=='Work')return;setTimeout(mount,300);setTimeout(mount,900);setTimeout(mount,1800)};boot();new MutationObserver(mount).observe(document.getElementById('root')||document.body,{childList:true,subtree:true});
})();
